/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as LoginManagerRouteImport } from './routes/login.manager'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSuppliersRouteImport } from './routes/dashboard.suppliers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSalesRouteImport } from './routes/dashboard.sales'
import { Route as DashboardSalariesRouteImport } from './routes/dashboard.salaries'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardInventoryAnalyticsRouteImport } from './routes/dashboard.inventory-analytics'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard.goals'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard.expenses'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginManagerRoute = LoginManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuppliersRoute = DashboardSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalariesRoute = DashboardSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryAnalyticsRoute =
  DashboardInventoryAnalyticsRouteImport.update({
    id: '/inventory-analytics',
    path: '/inventory-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/inventory-analytics': typeof DashboardInventoryAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/inventory-analytics': typeof DashboardInventoryAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/inventory-analytics': typeof DashboardInventoryAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/audit'
    | '/dashboard/expenses'
    | '/dashboard/goals'
    | '/dashboard/inventory'
    | '/dashboard/inventory-analytics'
    | '/dashboard/reports'
    | '/dashboard/salaries'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/login/admin'
    | '/login/manager'
    | '/dashboard/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/audit'
    | '/dashboard/expenses'
    | '/dashboard/goals'
    | '/dashboard/inventory'
    | '/dashboard/inventory-analytics'
    | '/dashboard/reports'
    | '/dashboard/salaries'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/login/admin'
    | '/login/manager'
    | '/dashboard'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/audit'
    | '/dashboard/expenses'
    | '/dashboard/goals'
    | '/dashboard/inventory'
    | '/dashboard/inventory-analytics'
    | '/dashboard/reports'
    | '/dashboard/salaries'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/login/admin'
    | '/login/manager'
    | '/dashboard/'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login/manager': {
      id: '/login/manager'
      path: '/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof LoginManagerRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suppliers': {
      id: '/dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof DashboardSuppliersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/salaries': {
      id: '/dashboard/salaries'
      path: '/salaries'
      fullPath: '/dashboard/salaries'
      preLoaderRoute: typeof DashboardSalariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory-analytics': {
      id: '/dashboard/inventory-analytics'
      path: '/inventory-analytics'
      fullPath: '/dashboard/inventory-analytics'
      preLoaderRoute: typeof DashboardInventoryAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardInventoryAnalyticsRoute: typeof DashboardInventoryAnalyticsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSalariesRoute: typeof DashboardSalariesRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuppliersRoute: typeof DashboardSuppliersRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardInventoryAnalyticsRoute: DashboardInventoryAnalyticsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSalariesRoute: DashboardSalariesRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuppliersRoute: DashboardSuppliersRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginManagerRoute: typeof LoginManagerRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginManagerRoute: LoginManagerRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
